title: Sample
#description: >- # your tagline
  Product Designer · Data Engineer · Portfolio & Projects
#baseurl: "" # biarkan kosong jika pakai username.github.io
#url: "https://username.github.io"
theme: automatic-app-landing-page
